source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'haml'
gem 'haml-rails'
gem 'bourbon', '~> 4.3.3'
gem 'normalize-rails'
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'middleman-sprockets'
gem 'masonry-rails'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'font-awesome-rails'
gem 'font-awesome-middleman'
gem 'middleman-gh-pages'
